"""
Self-Care AI — FastAPI Application
===================================
Entry point. Configures logging, initialises DB, seeds ChromaDB, and mounts routes.
"""

import logging
import sys
from contextlib import asynccontextmanager
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app.config import get_settings
from app.db.database import init_db
from app.routes.api import router

settings = get_settings()

# ── Logging ───────────────────────────────────────────────────────────────────

logging.basicConfig(
    level=getattr(logging, settings.log_level.upper(), logging.INFO),
    format="%(asctime)s | %(levelname)-8s | %(name)s | %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)],
)
logger = logging.getLogger(__name__)


# ── Lifespan (startup / shutdown) ─────────────────────────────────────────────

@asynccontextmanager
async def lifespan(app: FastAPI):
    logger.info("Starting Self-Care AI backend …")

    # Create DB tables
    init_db()
    logger.info("SQLite database initialised.")

    # Warm up ChromaDB (seeds knowledge base if empty)
    try:
        from app.services.memory import get_collection
        col = get_collection()
        logger.info(f"ChromaDB ready — {col.count()} wellness tips indexed.")
    except Exception as e:
        logger.warning(f"ChromaDB warm-up failed: {e}. RAG will be unavailable.")

    # Auto-train ML model if not found
    import os
    if not os.path.exists(settings.model_path):
        logger.info("ML model not found — running auto-training …")
        try:
            from app.ml.train import train
            train()
        except Exception as e:
            logger.warning(f"Auto-training failed: {e}. Rule-based fallback will be used.")

    yield

    logger.info("Shutting down Self-Care AI backend.")


# ── App ───────────────────────────────────────────────────────────────────────

app = FastAPI(
    title="Self-Care AI API",
    description=(
        "AI-powered self-care recommendation system. "
        "Submit daily check-ins and receive personalized wellness plans "
        "generated by a ML classifier + LLM pipeline."
    ),
    version="1.0.0",
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],   # tighten in production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(router)


@app.get("/", tags=["root"])
def root():
    return {
        "service": "Self-Care AI",
        "docs": "/docs",
        "health": "/api/v1/health",
    }
